# Generated by Django 5.0.1 on 2024-01-07 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name_plural': 'specialties'},
        ),
    ]
