# Generated by Django 5.0.1 on 2024-01-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_specialty_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='physician',
            name='degree_type',
            field=models.CharField(choices=[('DO', 'Doctor of Osteopathic Medicine'), ('MD', 'Doctor of Medicine')], default='MD', max_length=2),
        ),
    ]
