# Generated by Django 5.0.1 on 2024-01-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_physician_degree_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='physician',
            name='accepts_medicaid_medicare',
            field=models.BooleanField(default=False),
        ),
    ]
