# Generated by Django 5.0.1 on 2024-01-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_physician_accepts_medicaid_medicare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='accepts_medicaid_medicare',
            field=models.BooleanField(default=False, verbose_name='Accepts medicaid/medicare'),
        ),
    ]
