# Generated by Django 5.0.1 on 2024-01-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_physician_accepts_medicaid_medicare'),
    ]

    operations = [
        migrations.AddField(
            model_name='physician',
            name='taking_new_pts',
            field=models.BooleanField(default=False, verbose_name='Taking new patients'),
        ),
    ]
