# Generated by Django 5.0.1 on 2024-01-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_physician_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
