# Generated by Django 5.0.1 on 2024-01-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_physician_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='physician',
            name='address',
            field=models.CharField(default='N/A', max_length=250),
        ),
        migrations.AddField(
            model_name='physician',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=15),
        ),
    ]
