# Generated by Django 5.0.1 on 2024-01-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_physician_address_physician_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='physician',
            name='about_me',
            field=models.CharField(blank=True, max_length=1250, null=True),
        ),
        migrations.AlterField(
            model_name='physician',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='physician',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
